apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  type: {{ .Values.castService.service.type }}
  ports:
    - port: {{ .Values.castService.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: cast-service