apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: "{{ .Values.castService.image.repository }}:{{ .Values.castService.image.tag }}"
          imagePullPolicy: {{ .Values.castService.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "{{ .Values.castService.env.DATABASE_URI }}"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000