apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: cast-db
          image: "{{ .Values.castDb.image.repository }}:{{ .Values.castDb.image.tag }}"
          imagePullPolicy: {{ .Values.castDb.image.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.castDb.env.POSTGRES_USER }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.castDb.env.POSTGRES_PASSWORD }}"
            - name: POSTGRES_DB
              value: "{{ .Values.castDb.env.POSTGRES_DB }}"